### PR TITLE
Easy Config with Config-UI-X

### PR DESCRIPTION
**Pull request by donavanbecker**
@jonathandann added easy config for [config-ui-x](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI)

### CODE REVIEW

**Comment by jonathandann** [comment]
@donavanbecker Thanks for contributing! I really appreciate it.

**Comment by donavanbecker** [comment]
@jonathandann sorry for not looking at the config correctly and changing the header. When you updated the config there is an are you are missing in email description I believe.

**Comment by jonathandann** [comment]
@donavanbecker no need to apologise! I appreciate you making the change in the first place because I didn’t know that feature of the Homebridge config UI existed!

I’ll update the email description. Thanks for the information.

**Comment by donavanbecker** [comment]
No problem! Now once [0.9.10](https://github.com/jonathandann/homebridge-blink) is out everyone will have it!

**Pull request merged**
